#####################################
# Technology & Research Dep.
# Log file configuration
#
# TEMENOS (c) 2003, 2006
#
# This file contains configuration
# parameters for the log4j logger.
#
# Log Level = OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL
#
# Note : The 'File' must have only slashes '/' and never backslashes '\'
#
#####################################

log4j.rootLogger=FALSE
log4j.logger.common=INFO, file
log4j.logger.tcc=INFO, file
log4j.logger.channels=INFO, file
log4j.logger.ofsml=INFO, file


#####################################
#console   appender
#
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n

#####################################
#file appender
#
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n
log4j.appender.file.File=<log.directory>/global.log
log4j.appender.file.MaxFileSize=1024KB
log4j.appender.file.MaxBackupIndex=99

#####################################
#  Default SMTP appender
#
log4j.appender.smtp=com.temenos.log4jappenders.SMTPAppender
log4j.appender.smtp.layout=org.apache.log4j.PatternLayout
log4j.appender.smtp.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n
log4j.appender.smtp.SeverityFilter=ALL
log4j.appender.smtp.SMTPHost=YourMailServer #example mail.ibpmail.net
log4j.appender.smtp.SMTPPort=25 #The SMTP Server port
log4j.appender.smtp.SMTPTimeout=180000 #The timeout in milliseconds
log4j.appender.smtp.UseSSL=false #Encrypt communication (true or false)
log4j.appender.smtp.To=MailRecipients #example someone@mycompany.com;anotherone@anothercompany.com
log4j.appender.smtp.From=Sender #example log4j@mycompany.com
log4j.appender.smtp.Subject=MailSubject #example This is a test
log4j.appender.smtp.Header=Mail header if needed
log4j.appender.smtp.SMTPLogin=SMTP Server login if needed
log4j.appender.smtp.SMTPPassword=SMTP Server password if needed
log4j.appender.smtp.DropIfError=true

#####################################
#  Default RSS appender
#
log4j.appender.rss=com.temenos.log4jappenders.RSSAppender
log4j.appender.rss.layout=org.apache.log4j.PatternLayout
log4j.appender.rss.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n
log4j.appender.rss.SeverityFilter=ALL
# Supported Feed types (rss_0.90, rss_0.91, rss_0.92, rss_0.93, rss_0.94, rss_1.0 rss_2.0 or atom_0.3)
log4j.appender.rss.FeedType=rss_2.0
log4j.appender.rss.Author=RSSAppender
log4j.appender.rss.Title=RSS Log Appender Feed
log4j.appender.rss.Description=RSS feed created by RSSAppender & ROME
# Add the file name (xml) for the feed. Must be in a directory published by
# your web site : e.g. : C:/Inetpub/wwwroot/feed.xml
log4j.appender.rss.File=feed.xml
log4j.appender.rss.Link=http://localhost
log4j.appender.rss.Append=true
log4j.appender.rss.MaxMessages=50
log4j.appender.rss.MsgBufferSize=2
# Log <--> RSS Entry Map class (must implement interface RSSAppenderEntryMapper) default -
# log4j.appender.rss.RSSAppenderEntryMapClassName=com.temenos.log4jappenders.RSSAppenderEntryMapperImpl

#####################################
#  Default JMX appender
#
log4j.appender.jmx=com.temenos.log4jappenders.JMXNotifAppender
log4j.appender.jmx.SeverityFilter=INFO
log4j.appender.jmx.TypePrefix=com.temenos.tocf.tcs
log4j.appender.jmx.AppendSeverityToType=true
log4j.appender.jmx.DropIfError=true

#####################################
#  Default JDBC appender
#
log4j.appender.jdbc=com.temenos.log4jappenders.JDBCAppender
log4j.appender.jdbc.SeverityFilter=ALL
log4j.appender.jdbc.ConnectionString=yourConnectString #example for jdbc:mysql//localhost:3306/log4j
log4j.appender.jdbc.Driver=yourDriverString #example for mysql org.gjt.mm.mysql.Driver
log4j.appender.jdbc.DriverPath=../ext/yourJDBCdriver.jar
log4j.appender.jdbc.TypeINT=
log4j.appender.jdbc.TypeBIGINT=
log4j.appender.jdbc.TypeVARCHAR=
log4j.appender.jdbc.TypeTIMESTAMP=
log4j.appender.jdbc.TypeBLOB=
log4j.appender.jdbc.User=admin
log4j.appender.jdbc.Password=admin
log4j.appender.jdbc.Table=log4jevents
log4j.appender.jdbc.OverwriteTable=false
log4j.appender.jdbc.DropIfError=true

#####################################
#  Default Event Service appender
#
log4j.appender.event=com.temenos.log4jappenders.EventServiceAppender
log4j.appender.event.SeverityFilter=ALL
log4j.appender.event.ServerName=Server name or IP adddress of the Event Server
log4j.appender.event.CmdPortNo=9590
log4j.appender.event.PortNo=12000
log4j.appender.event.AppID=10
log4j.appender.event.DropIfError=true

#####################################
#  Create your own appenders here ...
#

#######################################
# Log4J Configuration Quick Reference:
# ====================================
#
# Priority order is DEBUG < INFO < WARN < ERROR < FATAL
#
# PatternLayout conversion characters:
#
# %c   Category of the logging event
# %C   Fully qualified class name of the caller
# %d   Date of the logging event  (example: %d{HH:mm:ss,SSS} )
# %F   File name where the logging request was issued (caution: extremely slow)
# %l   Location information of the caller (caution: extremely slow)
# %L   Line number from where the logging request was issued (caution: extremely slow)
# %m   Application-supplied message
# %M   Method name from where the logging request was issued (caution: extremely slow)
# %n   Line separator
# %p   Priority of the logging event
# %r   Number of milliseconds since the start of the application
# %t   Name of the thread that generated the logging event
# %x   Nested diagnotic context associated with the thread
# %%   A single percent sign
#
# Format modifiers examples:
#
# %20c     Left pad with spaces if category is less than 20 characters long
# %-20c    Right pad with spaces if category is less than 20 characters long
# %.30c    Truncate from the beginning if category is more than 30 chars long
# %20.30c  Left pad 20 chars + truncate from beginning if more than 30 chars
# %-20.30c Right pad 20 chars + truncate from beginning if more than 30 chars
#
# Examples:  "%r [%t] %-5p %c %x - %m"
#            "%-6r [%15.15t] %-5p %30.30c %x - %m"
#